### ISSUE TITLE
add a version tag

### ISSUE THREAD

**Issue by fiersik** [System64fumo/syspower#1]
Hi! Please add a version tag if there are ready-made releases.

This is necessary to build the package into the repository for ALT Linux.

**Comment by System64fumo** [comment]
Hello!
My programs don't use traditional versioning as i don't quite follow the stable release model.
This has been previously discussed on another project of mine [here](https://github.com/System64fumo/syshud/issues/1)
The closest thing to a version tag would be to use the commit date (as per -v output)

**Comment by fiersik** [comment]
Alas, this format is not suitable for building into a repository.

**Comment by System64fumo** [comment]
Can you not use v24.7.20 for instance?
If you wish to distribute my software on another platform/package manager (Other than Github/AUR) then i'm totally okay with you creating and maintaining the package in whichever method suits your distribution of choice,
Since i'm not really interested in maintaining a "stable" release nor providing pre built binaries.

**Comment by fiersik** [comment]
the git tag should be used as the version, or 0.1.0.COMMIT (not recommended)

**Comment by System64fumo** [comment]
I don't use git tags though?

**Comment by fiersik** [comment]
Yes, there are no tags

**Comment by System64fumo** [comment]
That's what i said though?
I don't plan on using tags if that's what you're asking?

**Comment by fiersik** [comment]
okay ,- ,

**Comment by fiersik** [comment]
Then I'll close it
